---
- hosts: localhost

  vars:
    desired_ansible_modules:
      - repo: https://github.com/mnussbaum/ansible-yay
        module: yay

  tasks:
    - debug:
        var: template_path
        
    - name: Template Ansible config
      template:
        src: "{{ template_path }}/config/ansible/ansible.cfg"
        dest: "{{ xdg_config_home }}/ansible/ansible.cfg"
        mode: 0600

    - name: symlink ansible config
      file:
        src: "{{ xdg_config_home }}/ansible/ansible.cfg"
        dest: "{{ home }}/.ansible.cfg"
        state: link

    - name: clone desired plugins
      git:
        repo: "{{ item.repo }}"
        dest: "{{ xdg_config_home }}/ansible/src/{{ item.module }}"
      with_items: "{{ desired_ansible_modules }}"

    - name: link desired plugins
      file:
        src: "{{ xdg_config_home }}/ansible/src/{{ item.module }}/{{ item.module }}"
        dest: "{{ xdg_config_home }}/ansible/modules/{{ item.module }}"
        state: link
      with_items: "{{ desired_ansible_modules }}"

