set nocompatible
filetype off
set rtp+=~/.vim/bundle/*/
call vundle#begin()

" Plugin manager
Plugin 'VundleVim/Vundle.vim'

" Seem to be working well
Plugin 'editorconfig/editorconfig-vim'
Plugin 'Valloric/YouCompleteMe'
Plugin 'vim-syntastic/syntastic'
Plugin 'myint/syntastic-extras'

" Look and Feel
Plugin 'phanviet/vim-monokai-pro'
Plugin 'scrooloose/nerdtree'

" Things to test
Plugin 'stephpy/vim-yaml'
Plugin 'pearofducks/ansible-vim'
Plugin 'fatih/vim-go'

" Things I'll get to soon
"Plugin 'tpope/vim-fugitive'
"Plugin 'airblade/vim-gitgutter'
"Plugin 'Xuyuanp/nerdtree-git-plugin'
"Plugin 'godlygeek/tabular'
"Plugin 'plasticboy/vim-markdown'
"Plugin 'scrooloose/nerdcommenter'
"Plugin 'chrisbra/vim-diff-enhanced'

" Things to play with
"Plugin 'hashivim/vim-packer'
"Plugin 'hashivim/vim-terraform'
"Plugin 'hashivim/vim-vagrant'
"Plugin 'hashivim/vim-vaultproject'

call vundle#end()

filetype plugin indent on

" Syntax stuff
syntax on

" Important settings
set encoding=utf-8
set mouse=a
set number
set modeline
set modelines=4

" look and feel
set termguicolors
colorscheme monokai_pro
autocmd vimenter * NERDTree

" Syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" Bindings

nnoremap <S-Tab> <<
inoremap <S-Tab> <C-d>
